### ISSUE TITLE
CreateDesign issue

### ISSUE THREAD

**Issue by louisgendron26** [CharlesJB/Stage_Louis_2016#16]
Bug report.
en generant l'objet brca <- fuzzysearch("brca",encode_df)
on tente de generer un design des fichiers de format bigbed :
     brcaDesign <- createDesign(brca, encode_df, fileFormat=c("bigBed"))

Les lignes 103-104 (de ma version) causent l'erreur

**Comment by CharlesJB** [comment]
Tous les fichiers de ChIP-Seq qui résultent du _peak calling_ ou d'une étape d'analyse subséquente n'ont plus besoin du contrôle car il n'est plus nécessaire. On pourrait régler le problème de la manière suivante:

``` r
  get_ctrl_design <- function(dt) {
    File <- clean_df[dataset == dt$ctrl, href]
    if (length(File) > 0) {
      data.table(File = File, Experiment = dt$replicates,
               Value = ID[2])
    } else {
      data.table(File = character(), Experiment = character(), Value = numeric())
    }   
  }
```
