### ISSUE TITLE
Généralisation du modèle de données

### ISSUE THREAD

**Issue by andronekomimi** [CharlesJB/Stage_Louis_2016#5]
Dans la version courante d'ENCODE nous avons découvert qu'il y a différents types de datasets : 
- annotation
- experiment
- matched-set
- project 
- reference 
- reference-epigenome 
- ucsc-browser-composite

La structure et le type de données disponibles sont différents. 
L'objectif est de déterminer une ossature commune afin de pouvoir fusionner tout les datasets en une seule entité.
Il faudra néanmoins trouver une manière de conserver les informations spécifiques de chacun type de dataset.

**Comment by louisgendron26** [comment]
J'ai merge les deux tables, encode_df$experiment(63 108,254) and
encode_df$dataset(57 by 4932) to a table 65 by 113,186

**Comment by CharlesJB** [comment]
@andronekomimi 
Quand tu auras un peu de temps, est-ce que tu pourrais faire le tour de la nouvelle table?
